snippet_start: "<pre>\n"
snippet_stop: "</pre>"
snippet_name_start: "@"
snippet_name: "<span class=\"snippet-name\">${name}</span>"
snippet_id: "<span class=\"snippet-id\" id=\"#xi-${id}\">&lt;${id}&gt;</span>"
snippet_name_stop: "#"
snippet_reference_start: "#"
snippet_reference: "<span class=\"snippet-reference\">${name}</span>"
snippet_reference_id: "<span class=\"snippet-id\">
                         <a href=\"#xi-${id}\">&lt;${id}&gt;</a>
                       </span>"
snippet_reference_stop: "@"
snippet_emission: "<span class=\"snippet-emission\">=> ${name}</span>
                   <span class=\"snippet-id\">
                      <a href=\"#xi-${id}\">&lt;${id}&gt;</a>
                   </span>"
