snippet_start: <pre>
snippet_stop: </pre>
snippet_name: "\n<span class=\"snippet-name\" id=\"#xi-${id}\">@${name}#</span> "
snippet_reference: "<span class=\"snippet-reference\">#${name}@</span>"
snippet_reference_id: "<span class=\"snippet-id\"><a href=\"#xi-${id}\">[${id}]</a></span>"
snippet_emission: "<span class=\"snippet-emission\">=> ${name}</span>
                   <span class=\"snippet-id\">
                      <a href=\"#xi-${id}\">[${id}]</a>
                   </span>"